export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT"
export const ERROR = "ERROR"
export const FETCH_SINGLE_PRODUCT_ID = "FETCH_SINGLE_PRODUCT_ID"

export const SET_LOADING = "SET_LOADING"
export const REMOVE_LOADING = "REMOVE_LOADING"

export const SHOW_PRODUCT_CARD = "SHOW_PRODUCT_CARD"
export const HIDE_PRODUCT_CARD = "HIDE_PRODUCT_CARD"
